### ISSUE TITLE
Remote Start/Stop nor Window/trunk sensors Available

### ISSUE THREAD

**Issue by naschenbrenner** [widewing/ha-toyota-na#97]
I just set up HomeAssistant in a Docker Container and installed HACS and this plugin and my 2021 Toyota Tacoma is showing window and trunk sensors as unavailable and I only see an option to Lock or Unlock my truck from the Controls section, no option to Start or Stop the engine. I have an active RemoteConnect subscription that expires in February 2025, I've attached my diagnostics file below, let me know if you need any additional info or would like me to try anything, thanks for creating such an awesome plug-in! 

[config_entry-toyota_na-01JE6FSJV0E12ATDNDRCBB244B.json](https://github.com/user-attachments/files/17995073/config_entry-toyota_na-01JE6FSJV0E12ATDNDRCBB244B.json)

**Comment by abnormalend** [comment]
I just set ha-toyota-na up on my HA install (2022 Tundra) and have similar issues.  I do see trunk, but I do not have remote start/stop showing in HA, and I do not see windows in HA.

[config_entry-toyota_na-01JEXM0Z835SSTCF1BYZRC44CP.json](https://github.com/user-attachments/files/18127565/config_entry-toyota_na-01JEXM0Z835SSTCF1BYZRC44CP.json)

**Comment by dvogelaar** [comment]
I also just set ha-toyota-na up on my HA OS install (2024 Tundra) I can see/do everything in HA as I can in the toyota app, except remotely starting and stopping. The only HA control I have is lock/unlock. but I can see if it is running/windows/doors etc via the sensors.

**Comment by Marty-McFly73** [comment]
Same as previous comment here.  I can remote start in the Toyota app but only have door lock/unlock function in HA.  No remote start control.

**Comment by AustinWisch** [comment]
I can remote start in the Toyota app but only have door lock/unlock function in HA. No remote start control, not sure if that is because on remote start I have to set the climate temperature and if I want the front or back windows to defrost.

**Comment by seang96** [comment]
Engine start / stop are an action and not exposed as entities currently. you can manually run actions in developer tools or you cn run actions in automations.

**Comment by Marty-McFly73** [comment]
> Engine start / stop are an action and not exposed as entities currently. you can manually run actions in developer tools or you cn run actions in automations.

Thanks for this.  Would you be able to point me somewhere that shows how to do that?

**Comment by Marty-McFly73** [comment]
> Engine start / stop are an action and not exposed as entities currently. you can manually run actions in developer tools or you cn run actions in automations.

This is amazing information.  I had no idea.  I do indeed see "toyota_na.engine_start" as an action in Developer Tools!  Thank you very much

**Comment by seang96** [comment]
Someone asked but I don't see their comment anymore. You can [use this link to go to developer actions ](https://my.home-assistant.io/redirect/developer_services/).

I have scripts you can use that use these with minor changes if you'd prefer. [Add scripts here](https://my.home-assistant.io/redirect/scripts/)

Refresh status:
```
alias: Refresh Solterra
sequence:
  - variables:
      last_changed: "{{ states('sensor.last_update_timestamp_2023_solterra_touring') }}"
  - repeat:
      sequence:
        - action: toyota_na.refresh
          data:
            vehicle: 4dfa477efa1ae248fb3fdc0cfcb426b0
        - delay:
            hours: 0
            minutes: 0
            seconds: 20
            milliseconds: 0
        - action: system_log.write
          metadata: {}
          data:
            level: info
            logger: Solterra_Scripts
            message: >-
              Refreshed {{
              states('sensor.last_update_timestamp_2023_solterra_touring') }}
      until:
        - condition: template
          value_template: >-
            {{ last_changed !=
            states('sensor.last_update_timestamp_2023_solterra_touring') }}
description: ""
mode: queued
max: 10

```

Remote Start: (it retries if it fails and locks doors since that improves success rate, it also notifies when it starts or fails 3 times, and if it starts and the car is plugged in, it starts my charger to not use battery)
```
alias: Remote Start Solterra
sequence:
  - repeat:
      count: 3
      sequence:
        - action: toyota_na.engine_start
          data:
            vehicle: 4dfa477efa1ae248fb3fdc0cfcb426b0
        - action: script.refresh_solterra
          metadata: {}
          data: {}
        - if:
            - condition: state
              entity_id: binary_sensor.remote_start_2023_solterra_touring
              state: "on"
          then:
            - data:
                message: Solterra remote started
              action: notify.ntfy
            - if:
                - condition: state
                  entity_id: switch.charger_charge_control
                  state: "off"
                - condition: state
                  entity_id: switch.charger_availability
                  state: "off"
                - condition: numeric_state
                  entity_id: sensor.ev_battery_level_2023_solterra_touring
                  above: 70
              then:
                - action: number.set_value
                  metadata: {}
                  data:
                    value: "15"
                  target:
                    entity_id: number.charger_maximum_current
                - action: homeassistant.turn_on
                  target:
                    entity_id: switch.charger_charge_control
                  data: {}
            - stop: Car is Running
          else:
            - action: toyota_na.door_lock
              data:
                vehicle: 4dfa477efa1ae248fb3fdc0cfcb426b0
            - condition: template
              value_template: "{{ repeat.last }}"
            - data:
                message: Solterra remote start failed.
              action: notify.ntfy
description: ""

```

Remote Stop: (never really used this one so its basically just the action) 
```
alias: Remote Stop Solterra
sequence:
  - action: toyota_na.engine_stop
    data:
      vehicle: 4dfa477efa1ae248fb3fdc0cfcb426b0
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - action: toyota_na.refresh
    data:
      vehicle: 4dfa477efa1ae248fb3fdc0cfcb426b0
description: ""

```

Remote Start / Stop:
```
alias: Remote Stop Solterra
sequence:
  - action: toyota_na.engine_stop
    data:
      vehicle: 4dfa477efa1ae248fb3fdc0cfcb426b0
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - action: toyota_na.refresh
    data:
      vehicle: 4dfa477efa1ae248fb3fdc0cfcb426b0
description: ""

```
